# Site settings
title: "Chris Pardue Blog"
email: cpardue@gmail.com
description: "Chris Pardue's Cybersecurity Blog"
baseurl: ""
url: "https://cpardue.github.io"
title_description: "My name is Chris Pardue.  I am an IT guy, trying to grow into a penetration tester.  To get there I am steadily learning more, and probably will be for many years.  Many drops of water will break a rock.  Information is the water and my head is the rock.  Only good can come of this?  The icons below link directly to my Twitter, Linkedin, HackTheBox, Github, and Reddit profiles."
title_image: "https://media-exp1.licdn.com/dms/image/C5603AQE3mz6irECQtg/profile-displayphoto-shrink_800_800/0/1517882536023?e=1621468800&v=beta&t=A360etwAFu-q10YoU_7IokyEU3wXenNAnVzPJjdyM98"
google_analytics: "UA-135634222-1"
disqus_account: 'disqus_cyAyVOiaL0'
github_repository: https://github.com/cpardue
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: cpardue09
github_username:  cpardue
instagram_username: 
reddit_username: c_pardue
linkedin_link: chris-pardue
hackthebox_username: 139580
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "<i class=\"fa fa-linkedin\"></i> &nbsp;<a href=\"https://www.linkedin.com/in/chris-pardue/\">LinkedIn</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/cpardue\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
