# Site settings
title: "Chris Pardue Blog"
email: cpardue@gmail.com
description: "Chris Pardue's Cybersecurity Blog"
baseurl: ""
url: "https://cpardue.github.io"
title_description: "A place to deposit my personal cybersecurity notes and findings as time passes by.  Making sprawling github repository pages is not cutting it, and I'm getting into way more interesting stuff now."
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: "UA-135634222-1"
disqus_account: 'disqus_cyAyVOiaL0'
github_repository: https://github.com/cpardue
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: cpardue09
github_username:  cpardue
instagram_username: 
reddit_username: c_pardue
linkedin_link: chris-pardue
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "<a href=\"https://www.linkedin.com/in/chris-pardue/\">LinkedIn</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/cpardue\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
